import 'package:get/get.dart';

//finnish, sweden, English
class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en_US": {
      "skip": "skip",
      "next": "next",
      "done": "done",
      "all rights reserved": "© ciyashop 2023 | all rights reserved",
      "search": "search",
      "cart": "cart",
      "account": "account",
      "wishlist": "wishlist",
      "title intro one": "E-Commerce App",
      "intro one": "Life is hard enough already. Let us make it a little easier.",
      "title intro two": "Choose Item",
      "intro two": "An exciting place for the whole family shop.",
      "title intro three": "Buy Item",
      "intro three": "The greatest journey of online shop.",
      "get started": "Get started",
      "shop now": "shop now",
      "view all": "view all",
      "off": "off",
      "items": "items",
      "remove": "remove",
      "edit": "edit",
      "add": "add",
      "move to bag": "move to bag",
      "ok": "ok",
      "yes": "yes",
      "no": "no",
      "all category": "all category",
      "login": "login",
      "sign in": "sign in",
      "sign out": "sign out",
      "my orders": "my orders",
      "my addresses": "my addresses",
      "choose currency": "choose currency",
      "choose language": "choose language",
      "download": "download",
      "my coupons": "my coupons",
      "coupons": "coupons",
      "my points": "my points",
      "about us": "about us",
      "account settings": "account settings",
      "notification": "notification",
      "notifications": "notifications",
      "product price": "product price",
      "other products vendor": "other products from this vendor",
      "no notification yet": "no notification yet",
      "remove all": "remove all",
      "remove all message": "are you sure want to remove all notification?",
      "contactus": "contact us",
      "rate the app": "rate the app",
      "clear history": "clear history",
      "clear": "clear",
      "expire": "expire : ",
      "remaining": "remaining : ",
      "recently viewed product": "recently viewed product",
      "clear history alert": "this permanently deletes your browse, search history from this device.",
      "setting": "setting",
      "notification permission": "permission for notification denied. please allow from settings.",
      "sign out alert": "do you really want to sign out from your account?",
      "camera": "camera",
      "gallery": "gallery",
      "no points earned": "no points earned",
      "purchase product earn points": "purchase product and earn points.",
      "event": "event",
      "date": "date",
      "points": "points",
      "browse some other item": "browse some other item",
      "no any product available": "no any product available",
      "email": "email",
      "password": "password",
      "old password": "old password",
      "new password": "new password",
      "retype password": "retype password",
      "forgot password": "forgot password?",
      "signup": "sign up",
      "or": "or",
      "select country": "select a country",
      "close": "close",
      "end of the sale": "end of the sale",
      "don't have account": "don't have an account? sign up now",
      "sign up now": "sign up now",
      "already have account": "already have an account? sign in now",
      "sign in now": "sign in now",
      "enter email": "enter email address",
      "enter valid email": "enter valid email address",
      "enter password": "enter password",
      "enter confirm password": "enter confirm password",
      "enter contact no": "enter contact number",
      "confirm password match": "password and confirm password does not match",
      "enter current password": "enter your current password",
      "password not correct": "your email address or password is not correct",
      "enter new password": "enter your new password",
      "password changed successfully": "password changed successfully",
      "provide email to facebook": "provide email id to your facebook account",
      "enter username": "enter user name",
      "no currency found": "no currency found",
      "no language found": "no languages found",
      "email id": "email id",
      "username": "user name",
      "confirm password": "confirm password",
      "add address": "add new address",
      "please add address": "please add address",
      "billing address": "billing address",
      "shipping address": "shipping address",
      "add billing address": "add billing address",
      "add shipping address": "add shipping address",
      "remove address": "are you sure want to remove address?",
      "name": "name",
      "first name": "first name",
      "last name": "last name",
      "zipcode": "zipcode",
      "address1": "address1",
      "address2": "address2",
      "city town": "city/town",
      "state": "state",
      "company": "company",
      "phone number": "phone number",
      "save": "save",
      "cancel": "cancel",
      "scratch here code": "scratch here to get code",
      "scratch here coupon code": "scratch here to get coupon code.",
      "coupon code": "coupon code",
      "coupon code copied": "coupon code is copied to your clipboard",
      "no rewards yet": "no rewards yet..!!",
      "version": "version",
      "terms & condition": "terms & condition",
      "privacy policy": "privacy policy",
      "follow us": "follow us",
      "more about us": "more about us",
      "account setting": "account setting",
      "date of birth": "date of birth",
      "gender": "gender",
      "mobile number": "mobile number",
      "change password": "change password",
      "deactivate account": "delete account",
      "confirm deactivation": "confirm deletion",
      "information updated success": "information updated successfully",
      "deactivated success": "your account is deactivated successfully",
      "confirm deactivate": "are you sure to deactivate your profile? \n if yes then to re-active your profile you need to contact admin.",
      "contact number": "contact number",
      "subject": "subject",
      "message": "message",
      "send": "send",
      "enter name": "enter your name",
      "enter subject": "enter subject",
      "enter message": "please enter message",
      "message sent": "message sent",
      "order id": "order id:",
      "total amount": "total amount:",
      "quantity": "quantity:",
      "details": "details",
      "retry": "retry",
      "order details": "order details",
      "cancel order": "cancel order",
      "no order yet": "no order yet",
      "no order description": "simply browse , create a wish list or make a purchase.",
      "tracking number is": "tracking number is",
      "delivered soon": "delivered soon",
      "order pending state": "order is in pending state",
      "order under processing": "order is under processing",
      "order on hold": "order is on-hold",
      "delivered": "delivered",
      "delivered on": "delivered on",
      "order cancelled": "order is cancelled",
      "refunded order": "you are refunded for this order",
      "order failed": "order is failed",
      "deliver soon": "your order will be deliver soon",
      "order": "order",
      "was placed": "was placed on",
      "and currently": "and currently",
      "order cancelled success": "order cancelled successfully.",
      "thank you": "thank you",
      "order placed success": "your order is placed successfully.",
      "notify in few moments": "you will notify in few moments.",
      "shopping bag": "shopping bag",
      "continue shopping": "continue shopping",
      "add to cart message": "simply browse and add item to cart.",
      "add to wish list message": "simply browse and add item to wishlist.",
      "item already in cart": "item already in cart",
      "cart is empty": "cart is empty",
      "no product found": "no product found",
      "delete": "delete",
      "continue to checkout": "continue to checkout",
      "search list empty": "search list is empty",
      "browse our store": "browse our store and take a look at other items to buy.",
      "search here": "search here...",
      "reset your world": "reset your world",
      "reset password description": "it's often forgotten that password things. enter your email address below and click on the 'request password reset' button. we will contact you shortly!",
      "request password reset": "request password reset",
      "reset your password": "reset your password",
      "enter pin": "enter pin that we have sent you in your registered email address.",
      "set new password": "set new password",
      "pin in correct": "entered pin is not correct",
      "password not match": "password and confirm password does not match",
      "pin": "pin",
      "verification code": "verification code",
      "verification code description": "verification code is sent to the mobile number. please enter verification code.",
      "validate otp": "validate otp",
      "resend otp": "resend otp",
      "enter verification code": "enter verification code",
      "otp sent again": "otp is sent again on",
      "password update success": "your password updated successfully",
      "you have points": "you have points",
      "sub total": "sub total",
      "shipping": "shipping",
      "amount payable": "amount payable",
      "payment method": "payment method:",
      "payment details": "payment details",
      "sort by": "sort by",
      "filter": "filter",
      "color": "color",
      "size": "size",
      "price range": "price range",
      "select all": "select all",
      "category": "category",
      "brand": "brand",
      "rating": "rating",
      "clear filter": "clear filter",
      "availability": "availability",
      "out of stock": "out of stock",
      "in stock": "in stock",
      "newest first": "newest first",
      "popularity": "popularity",
      "price low to high": "price - low to high",
      "price high to low": "price - high to low",
      "buy now": "buy now",
      "add to cart": "add to cart",
      "info": "info",
      "delivery options": "delivery options",
      "enter your pin code": "enter your pin code",
      "check": "check",
      "sold by": "sold by",
      "seller information": "seller information",
      "contact seller": "contact seller",
      "view store": "view store",
      "quick overview": "quick overview",
      "product details": "product details",
      "more": "more...",
      "ratings & reviews": "ratings & reviews",
      "ratings": "ratings",
      "reviews": "reviews",
      "review": "review",
      "rate & write review": "rate and write review",
      "view all reviews": "view all reviews",
      "rate product": "rate product",
      "comment": "comment",
      "submit": "submit",
      "image": "image",
      "quick": "quick",
      "remove from cart": "are you sure want to remove from cart?",
      "remove from wishlist": "are you sure want to remove from wishlist?",
      "item added wishlist": "item added to your wish list.",
      "item removed wishlist": "item removed from your wish list.",
      "item added cart": "item added to your cart successfully",
      "combination not exists": "this combination doesn't exist. choose another variant.",
      "goto cart": "go to cart",
      "related products": "related products",
      "give rating": "please give your ratings",
      "available at": "available at",
      "available": "available",
      "cash on delivery": "cash on delivery",
      "not available": "not available",
      "delivery data help text": "delivery date help text",
      "pin code not blank": "pincode should not be blank.",
      "enter valid pincode": "please enter valid pincode",
      "invalid contact no": "invalid contact number",
      "whatsapp not installed": "whatsapp is not installed on your device.",
      "rating url not available": "rating url is not set",
      "geofence message": "you have entered in our shop region",
      "website not valid": "website is not valid",
      "wallet balance": "wallet balance",
      "wallet": "wallet",
      "wallet transaction history": "wallet transaction history",
      "order placed failure": "order canceled",
      "order placed failure submessage": "unfortunately your order cannot be processed as the originating bank/merchant has declined your transaction.",
      "technical issue": "there is some technical problem. please try after some time.",
      "enter first name": "please enter first name",
      "enter last name": "please enter last name",
      "enter pin code": "please enter pincode",
      "enter address1": "please enter address1",
      "enter address2": "please enter address2",
      "enter phone number": "please enter phone number",
      "enter company": "please enter company",
      "logout not exist user": "your account is deleted by admin. you must have to logout."
    },
    "es_ES": {
      "skip": "saltar",
      "next": "siguiente",
      "done": "hecho",
      "all rights reserved": "© ciyashop 2023 | todos los derechos reservados",
      "search": "buscar",
      "cart": "carrito",
      "account": "cuenta",
      "wishlist": "lista de deseos",
      "title intro one": "Aplicación de Comercio Electrónico",
      "intro one": "La vida ya es bastante difícil. Déjanos hacerlo un poco más fácil.",
      "title intro two": "Elegir Artículo",
      "intro two": "Un lugar emocionante para que toda la familia compre.",
      "title intro three": "Comprar Artículo",
      "intro three": "El mayor viaje de la tienda en línea.",
      "get started": "Empezar",
      "shop now": "comprar ahora",
      "view all": "ver todo",
      "off": "descuento",
      "items": "artículos",
      "remove": "eliminar",
      "edit": "editar",
      "add": "añadir",
      "move to bag": "mover al bolso",
      "ok": "ok",
      "yes": "sí",
      "no": "no",
      "all category": "todas las categorías",
      "login": "iniciar sesión",
      "sign in": "registrarse",
      "sign out": "cerrar sesión",
      "my orders": "mis pedidos",
      "my addresses": "mis direcciones",
      "choose currency": "elegir moneda",
      "choose language": "elegir idioma",
      "download": "descargar",
      "my coupons": "mis cupones",
      "coupons": "cupones",
      "my points": "mis puntos",
      "about us": "sobre nosotros",
      "account settings": "configuración de cuenta",
      "notification": "notificación",
      "notifications": "notificaciones",
      "product price": "precio del producto",
      "other products vendor": "otros productos de este vendedor",
      "no notification yet": "aún no hay notificaciones",
      "remove all": "eliminar todo",
      "remove all message": "¿Estás seguro de que deseas eliminar todas las notificaciones?",
      "contactus": "contáctanos",
      "rate the app": "calificar la aplicación",
      "clear history": "borrar historial",
      "clear": "borrar",
      "expire": "expira: ",
      "remaining": "restante: ",
      "recently viewed product": "producto visto recientemente",
      "clear history alert": "esto elimina permanentemente tu historial de navegación y búsqueda de este dispositivo.",
      "setting": "configuración",
      "notification permission": "permiso para notificaciones denegado. por favor, permite desde la configuración.",
      "sign out alert": "¿realmente quieres cerrar sesión en tu cuenta?",
      "camera": "cámara",
      "gallery": "galería",
      "no points earned": "no se han ganado puntos",
      "purchase product earn points": "compra productos y gana puntos.",
      "event": "evento",
      "date": "fecha",
      "points": "puntos",
      "browse some other item": "navega por otros artículos",
      "no any product available": "no hay productos disponibles",
      "email": "correo electrónico",
      "password": "contraseña",
      "old password": "contraseña antigua",
      "new password": "nueva contraseña",
      "retype password": "vuelve a escribir la contraseña",
      "forgot password": "¿Olvidaste la contraseña?",
      "signup": "registrarse",
      "or": "o",
      "select country": "seleccionar país",
      "close": "cerrar",
      "end of the sale": "fin de la venta",
      "don't have account": "¿no tienes cuenta? regístrate ahora",
      "sign up now": "regístrate ahora",
      "already have account": "¿ya tienes cuenta? inicia sesión ahora",
      "sign in now": "inicia sesión ahora",
      "enter email": "introduce la dirección de correo electrónico",
      "enter valid email": "introduce una dirección de correo electrónico válida",
      "enter password": "introduce la contraseña",
      "enter confirm password": "introduce la contraseña de confirmación",
      "enter contact no": "introduce el número de contacto",
      "confirm password match": "la contraseña y la confirmación de la contraseña no coinciden",
      "enter current password": "introduce tu contraseña actual",
      "password not correct": "tu dirección de correo electrónico o contraseña no es correcta",
      "enter new password": "introduce tu nueva contraseña",
      "password changed successfully": "contraseña cambiada con éxito",
      "provide email to facebook": "proporciona la dirección de correo electrónico de tu cuenta de Facebook",
      "enter username": "introduce el nombre de usuario",
      "no currency found": "no se ha encontrado ninguna moneda",
      "no language found": "no se han encontrado idiomas",
      "email id": "id de correo electrónico",
      "username": "nombre de usuario",
      "confirm password": "confirmar contraseña",
      "add address": "añadir nueva dirección",
      "please add address": "por favor, añade una dirección",
      "billing address": "dirección de facturación",
      "shipping address": "dirección de envío",
      "add billing address": "añadir dirección de facturación",
      "add shipping address": "añadir dirección de envío",
      "remove address": "¿Estás seguro de que deseas eliminar la dirección?",
      "name": "nombre",
      "first name": "nombre",
      "last name": "apellido",
      "zipcode": "código postal",
      "address1": "dirección1",
      "address2": "dirección2",
      "city town": "ciudad/pueblo",
      "state": "estado",
      "company": "empresa",
      "phone number": "número de teléfono",
      "save": "guardar",
      "cancel": "cancelar",
      "scratch here code": "rasca aquí para obtener el código",
      "scratch here coupon code": "rasca aquí para obtener el código de cupón.",
      "coupon code": "código de cupón",
      "coupon code copied": "el código de cupón se ha copiado al portapapeles",
      "no rewards yet": "aún no hay recompensas..!!",
      "version": "versión",
      "terms & condition": "términos y condiciones",
      "privacy policy": "política de privacidad",
      "follow us": "síguenos",
      "more about us": "más sobre nosotros",
      "account setting": "configuración de la cuenta",
      "date of birth": "fecha de nacimiento",
      "gender": "género",
      "mobile number": "número de móvil",
      "change password": "cambiar contraseña",
      "deactivate account": "eliminar cuenta",
      "confirm deactivation": "confirmar eliminación",
      "information updated success": "información actualizada con éxito",
      "deactivated success": "tu cuenta ha sido eliminada con éxito",
      "confirm deactivate": "¿Estás seguro de que deseas desactivar tu perfil? \n si es así, para reactivar tu perfil necesitas contactar con el administrador.",
      "contact number": "número de contacto",
      "subject": "asunto",
      "message": "mensaje",
      "send": "enviar",
      "enter name": "introduce tu nombre",
      "enter subject": "introduce el asunto",
      "enter message": "por favor, introduce el mensaje",
      "message sent": "mensaje enviado",
      "order id": "id de pedido:",
      "total amount": "monto total:",
      "quantity": "cantidad:",
      "details": "detalles",
      "retry": "reintentar",
      "order details": "detalles del pedido",
      "cancel order": "cancelar pedido",
      "no order yet": "aún no hay pedidos",
      "no order description": "simplemente navega, crea una lista de deseos o realiza una compra.",
      "tracking number is": "el número de seguimiento es",
      "delivered soon": "se entregará pronto",
      "order pending state": "el pedido está en estado pendiente",
      "order under processing": "el pedido está en proceso",
      "order on hold": "el pedido está en espera",
      "delivered": "entregado",
      "delivered on": "entregado el",
      "order cancelled": "el pedido está cancelado",
      "refunded order": "has sido reembolsado por este pedido",
      "order failed": "el pedido ha fallado",
      "deliver soon": "tu pedido será entregado pronto",
      "order": "pedido",
      "was placed": "fue realizado el",
      "and currently": "y actualmente",
      "order cancelled success": "pedido cancelado con éxito.",
      "thank you": "gracias",
      "order placed success": "tu pedido ha sido realizado con éxito.",
      "notify in few moments": "serás notificado en unos momentos.",
      "shopping bag": "bolsa de compras",
      "continue shopping": "continuar comprando",
      "add to cart message": "simplemente navega y añade artículos al carrito.",
      "add to wish list message": "simplemente navega y añade artículos a la lista de deseos.",
      "item already in cart": "el artículo ya está en el carrito",
      "cart is empty": "el carrito está vacío",
      "no product found": "no se ha encontrado ningún producto",
      "delete": "eliminar",
      "continue to checkout": "continuar con la compra",
      "search list empty": "la lista de búsqueda está vacía",
      "browse our store": "navega por nuestra tienda y echa un vistazo a otros artículos para comprar.",
      "search here": "buscar aquí...",
      "reset your world": "restablecer tu mundo",
      "reset password description": "a menudo se olvida esa cosa de la contraseña. introduce tu dirección de correo electrónico a continuación y haz clic en el botón 'solicitar restablecimiento de contraseña'. ¡Nos pondremos en contacto contigo en breve!",
      "request password reset": "solicitar restablecimiento de contraseña",
      "reset your password": "restablecer tu contraseña",
      "enter pin": "introduce el pin que te hemos enviado a tu dirección de correo electrónico registrada.",
      "set new password": "establecer nueva contraseña",
      "pin in correct": "el pin introducido no es correcto",
      "password not match": "la contraseña y la confirmación de la contraseña no coinciden",
      "pin": "pin",
      "verification code": "código de verificación",
      "verification code description": "se ha enviado el código de verificación al número de móvil. por favor, introduce el código de verificación.",
      "validate otp": "validar otp",
      "resend otp": "reenviar otp",
      "enter verification code": "introduce el código de verificación",
      "otp sent again": "el otp se ha enviado nuevamente a",
      "password update success": "tu contraseña se ha actualizado con éxito",
      "you have points": "tienes puntos",
      "sub total": "subtotal",
      "shipping": "envío",
      "amount payable": "monto a pagar",
      "payment method": "método de pago:",
      "payment details": "detalles de pago",
      "sort by": "ordenar por",
      "filter": "filtro",
      "color": "color",
      "size": "tamaño",
      "price range": "rango de precios",
      "select all": "seleccionar todo",
      "category": "categoría",
      "brand": "marca",
      "rating": "clasificación",
      "clear filter": "borrar filtro",
      "availability": "disponibilidad",
      "out of stock": "agotado",
      "in stock": "en stock",
      "newest first": "más nuevos primero",
      "popularity": "popularidad",
      "price low to high": "precio - de bajo a alto",
      "price high to low": "precio - de alto a bajo",
      "buy now": "comprar ahora",
      "add to cart": "añadir al carrito",
      "info": "info",
      "delivery options": "opciones de entrega",
      "enter your pin code": "introduce tu código postal",
      "check": "verificar",
      "sold by": "vendido por",
      "seller information": "información del vendedor",
      "contact seller": "contactar al vendedor",
      "view store": "ver tienda",
      "quick overview": "vista rápida",
      "product details": "detalles del producto",
      "more": "más...",
      "ratings & reviews": "calificaciones y reseñas",
      "ratings": "calificaciones",
      "reviews": "reseñas",
      "review": "reseña",
      "rate & write review": "calificar y escribir reseña",
      "view all reviews": "ver todas las reseñas",
      "rate product": "calificar producto",
      "comment": "comentario",
      "submit": "enviar",
      "image": "imagen",
      "quick": "rápido",
      "remove from cart": "¿Estás seguro de que deseas eliminarlo del carrito?",
      "remove from wishlist": "¿Estás seguro de que deseas eliminarlo de la lista de deseos?",
      "item added wishlist": "artículo añadido a tu lista de deseos.",
      "item removed wishlist": "artículo eliminado de tu lista de deseos.",
      "item added cart": "artículo añadido a tu carrito con éxito",
      "combination not exists": "esta combinación no existe. elige otra variante.",
      "goto cart": "ir al carrito",
      "related products": "productos relacionados",
      "give rating": "por favor, da tu calificación",
      "available at": "disponible en",
      "available": "disponible",
      "cash on delivery": "contra reembolso",
      "not available": "no disponible",
      "delivery data help text": "texto de ayuda de la fecha de entrega",
      "pin code not blank": "el código postal no debe estar en blanco.",
      "enter valid pincode": "por favor, introduce un código postal válido",
      "invalid contact no": "número de contacto no válido",
      "whatsapp not installed": "WhatsApp no está instalado en tu dispositivo.",
      "rating url not available": "la URL de calificación no está configurada",
      "geofence message": "has entrado en la región de nuestra tienda",
      "website not valid": "el sitio web no es válido",
      "wallet balance": "saldo de la cartera",
      "wallet": "cartera",
      "wallet transaction history": "historial de transacciones de la cartera",
      "order placed failure": "pedido cancelado",
      "order placed failure submessage": "desafortunadamente, tu pedido no se puede procesar ya que el banco/mercante originario ha rechazado tu transacción.",
      "technical issue": "hay un problema técnico. por favor, intenta de nuevo más tarde.",
      "enter first name": "por favor, introduce el nombre",
      "enter last name": "por favor, introduce el apellido",
      "enter pin code": "por favor, introduce el código postal",
      "enter address1": "por favor, introduce la dirección1",
      "enter address2": "por favor, introduce la dirección2",
      "enter phone number": "por favor, introduce el número de teléfono",
      "enter company": "por favor, introduce la empresa",
      "logout not exist user": "tu cuenta ha sido eliminada por el administrador. debes cerrar sesión."
    }
  };
}
